service: backend
configValidationMode: warn
provider:
  name: aws
  runtime: rust
  memorySize: 128
  timeout: 20
  stage: dev
  region: eu-west-2
  environment:
    TABLE_NAME:
      Ref: JobPostsTable
    JOB_POSTS_QUEUE_URL:
      Ref: JobPostsQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:DescribeTable
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
            - dynamodb:BatchGetItem
          Resource:
            - "Fn::GetAtt": [JobPostsTable, Arn]
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:SendMessageBatch
            - sqs:DeleteMessage
            - sqs:DeleteMessageBatch
          Resource:
            - "Fn::GetAtt": [JobPostsQueue, Arn]

package:
  individually: true

plugins:
  - serverless-rust
  - serverless-dotenv-plugin

functions:
  hello:
    # handler value syntax is `{cargo-package-name}.{bin-name}`
    # or `{cargo-package-name}` for short when you are building a
    # default bin for a given package.
    handler: api.hello-world
    events:
      - http:
          path: hello
          method: get
          cors: true
  json_try:
    handler: api.json-try
    events:
      - http:
          path: json
          method: post
          cors: true
  data_collector:
    handler: api.data-collector
    events:
      - schedule: rate(12 hours)
    timeout: 600
  process_job_post:
    handler: api.process-job-post
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - JobPostsQueue
              - Arn
    timeout: 60
  process_all_job_posts:
    handler: api.process-all-job-posts

resources:
  Resources:
    JobPostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "${opt:stage}-job-posts"
        AttributeDefinitions:
          - AttributeName: jobId
            AttributeType: N
        KeySchema:
          - AttributeName: jobId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    JobPostsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "${opt:stage}-job-posts-queue"
        VisibilityTimeout: 120

custom:
  rust:
    dockerless: true
