#[tokio::test]
#[tracing_test::traced_test]
pub async fn preprocess() {
    use crate::modules::gpt::preprocess;

    let example_description = " <p>Frontend Developer - Top 5 FX Trading Platform in the world!</p> <p>Are you a Senior Frontend Developer actively looking for a new challenge? Would you like to work for one of the top 5 FX trading platform providers in the world? If so, our client has the perfect role for you!</p> <p>This business is a world leader in trading solutions for the global financial marketplace. They were founded as a start-up in 2017 and has grown from 1 person to 130 in 5 years. They are now a €1 Billion dollar company and there is now slowing down in the  planned growth roadmap for the next couple of years! The are currently looking to add a skilled Senior Frontend Developer to join their dynamic team.</p> <p>The Senior Frontend Developer will create feature-rich user interfaces for FX trading. The frontend applications are beautifully designed and engineered for high-touch, professional traders. The UI components are sophisticated real-time, single page webapps  build on HTML5 technology.</p> <p>You will collaborate with your peers, product team, UI designers, backends, QA and SCRUM masters to build a world leading FX EMS.</p> <p>Daily duties for the Senior Frontend Developer will include:</p> <ul> <li>Directly contributing to the development of a world leading FX trading platform.</li><li>Work on greenfield projects contributing to a platform which has over €1 billion dollars' worth of trades a day.</li><li>Create, improve, optimise and maintain all elements of frontend software and associated APIs.</li><li>Operate within a full-stack development squad and drive high quality products to production.</li><li>Partner with all teams and all levels to achieve business aims in a cost effective and timely manner.</li></ul> <p>The successful candidate will have a combination of the following skills and experience:</p> <ul> <li>Expert, hands-on modern syntax JavaScript and TypeScript.</li><li>Experience with the React framework and ideally Rx.js.</li><li>Well versed in the use of CSS3 to style frontend applications.</li><li>Good knowledge of browsers and containers, including Chrome, Chromium and Electron.</li><li>Excellent knowledge of using and designing REST APIs and web-socket solutions.</li><li>Agile practices such as XP, pair programming, test driven development and SCRUM.</li><li>You will need to be product driven, enthusiastic for change, self-motivated, well organised, adaptable and a quick learner.</li></ul> <p>Salary &amp; Benefits:</p> <ul> <li>&#163;120k</li><li>Bonus - 20-25%</li><li>Pension</li><li>28 Days Holiday</li></ul> <p>To apply for this exceptional opportunity please send your CV to </p> ";

    let preprocessed_description = preprocess::preprocess(example_description).unwrap();

    tracing::info!("{:?}", preprocessed_description);

    assert_eq!(preprocessed_description, "frontend develop trade platform senior frontend develop activ challeng trade platform provid client perfect role busi leader trade solut global financi marketplac found start grown person dollar compani slow plan growth roadmap coupl add skill senior frontend develop dynam team senior frontend develop creat featur rich user interfac trade frontend applic beauti design engin touch profession trader ui compon sophist real time singl webapp build html5 technolog collabor peer product team ui design backend scrum master build lead em daili duti senior frontend develop includ contribut develop lead trade platform greenfield project contribut platform dollar worth trade day creat improv optimis maintain element frontend softwar api oper full stack develop squad drive qualiti product product partner team level achiev busi aim cost effect time manner success candid combin skill experi expert hand modern syntax javascript typescript experi react framework ideal rx js vers css3 style frontend applic knowledg browser contain includ chrome chromium electron excel knowledg design rest api socket solut agil practic xp pair program driven develop scrum product driven enthusiast chang motiv organis adapt quick learner salari benefit 120k bonus pension day holiday appli except opportun send");
}

#[tokio::test]
#[tracing_test::traced_test]
pub async fn preprocess_no_html() {
    use crate::modules::gpt::preprocess;

    let example_description = "**Full Stack Engineer - Java/React** Salary: Up to £75000 + benefits Location: Fully remote You must be available to go to face-to-face team meetings in Oxford 1-2 times a month. **Like sound of working on projects using AI-augmented coding to change way Developers code?** **Enjoy a Backend and Frontend mix?** An expanding software house using AI for code looking for a Full Stack Engineer to join their team They a spin-out from Oxford University Their products help developers and organisations to achieve faster delivery of high-quality code This company currently has over 50 employees and received over $30million in Series A funding. Tech stack: **Java 50% React 50% Spring PostgreSQL Docker Kubernetes** They hiring across all levels of seniority from Mid to Senior Full Stack Engineers. They believe in clean code and BDD/TDD and i.e. something they really value as well as working with agile methodologies and with CI/CD pipelines You will design and develop fast and reliable systems and work as part of a team delivering customers via a fantastic user experience in a fast-paced rapidly changing environment. Benefits for this Full Stack Engineer opportunity: * Shares * 8% non-contributory pension * Medical dental and life insurance **If you're excited about this opportunity to join a growing AI scale-up as a Full Stack Engineer - Java/React apply now!** Understanding Recruitment is serving as employment agency for this job opening.";

    let preprocessed_description = preprocess::preprocess(example_description).unwrap();

    tracing::info!("{:?}", preprocessed_description);

    assert_eq!(preprocessed_description, "full stack engin java react salari benefit locat remot team meet oxford time month sound project augment code chang develop code enjoy backend frontend mix expand softwar hous code full stack engin team spin oxford univers product develop organis achiev faster deliveri qualiti code compani employe receiv 30million seri fund tech stack java react spring postgresql docker kubernet hire level senior mid senior full stack engin clean code bdd tdd agil methodolog pipelin design develop fast reliabl system team deliv custom fantast user experi fast pace rapid chang environ benefit full stack engin opportun share contributori pension medic dental life insur excit opportun grow scale full stack engin java react appli understand recruit serv employ agenc job");
}
